# https://taskfile.dev

version: '3'

tasks:
  build-ringss:
    cmds:
      - go build -o bin/ringss cmd/ringss/main.go
  run:
    cmds:
      - ./bin/ringss
    deps: [build-ringss]
  env:
    cmds:
      - ./bin/ringss -env
    deps: [build-ringss]
